consul:
    image: hornoo/virtassignconsulcontainer
    hostname: $HOSTNAME
    container_name: larry_agent
    command: -server -advertise $PUBLIC_IP -bootstrap-expect 3
    ports:
     - 8300:8300
     - 8301:8301
     - 8301:8301/udp
     - 8302:8302 
     - 8302:8302/udp
     - 8400:8400
     - 8500:8500
     - 53:53/udp
nginxProxyWS:
    image: hornoo/virtassignlarryproxy
    container_name: nginx_proxy_ws
    ports:
     - 80:80
    dns: 172.17.42.1
