consul:
    image: hornoo/virtassignconsulcontainer
    hostname: $HOSTNAME
    container_name: curly_agent
    command: -server -advertise $PUBLIC_IP -join $JOIN_IP
    ports:
     - 8300:8300
     - 8301:8301
     - 8301:8301/udp
     - 8302:8302 
     - 8302:8302/udp
     - 8400:8400
     - 8500:8500
     - 53:53/udp
flask_app:
    image: hornoo/virtassignflaskserver
    hostname: $PUBLIC_IP
    container_name: curly_flask_app
    ports:
    - 5000:5000 
